config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('django-rq/', include('django_rq.urls')),

    path('', include(("urban_piper.core.urls", "core"), namespace="core")),
    path('accounts/', include(("urban_piper.users.urls", "core"), namespace="users")),

]

urban_piper/core/urls.py
from django.contrib import admin
from django.urls import path, include
from urban_piper.core import views

urlpatterns = [
    path('', views.index, name="index"),
    path('dp/', views.DeliveryPersonView.as_view(), name="delivery_person"),
    path('sm/', views.StorageManagerView.as_view(), name="storage_manager"),

]

urban_piper/core/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.core.serializers.json import DjangoJSONEncoder
from django.db.models.signals import pre_save
from django.dispatch import receiver
from urban_piper.users.models import User
import json


class DeliveryTaskState(models.Model):
    state_choices = (
        ("new", "New"),
        ("accepted", "Accepted"),
        ("completed", "Completed"),
        ("declined", "Declined"),
        ("cancelled", "Cancelled"),
    )
    state = models.CharField(choices=state_choices,
                             default="new", max_length=12,
                             db_index=True,
                             unique=True
                             )

    def __str__(self):
        return "%s" % (self.state)

    class Meta:
        verbose_name = _("DeliveryTaskState")
        verbose_name_plural = _("DeliveryTaskStates")


class DeliveryTaskManager(models.Manager):
    def get_object_in_json(self, task_id):
        task = self.get(id=task_id)
        return json.loads(json.dumps({
            "id": task.id,
            "title": task.title,
            "priority": task.priority,
            "creation_at": task.creation_at,
            "created_by": task.created_by.username
        }, cls=DjangoJSONEncoder))


class DeliveryTask(models.Model):
    priority_choice_fields = (
        ("high", "High"),
        ("medium", "Medium"),
        ("low", "Low")
    )
    title = models.CharField(max_length=180, db_index=True)
    priority = models.CharField(
        max_length=10, choices=priority_choice_fields, default="low")
    creation_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User,
                                   on_delete=models.CASCADE,
                                   limit_choices_to={
                                       "is_storage_manager": True,
                                       "is_delivery_person": False,
                                   },
                                   related_name="created_by_sm",
                                   db_index=True
                                   )
    states = models.ManyToManyField(
        DeliveryTaskState, through="DeliveryStateTransition")

    objects = DeliveryTaskManager()

    class Meta:
        verbose_name = _("DeliveryTask")
        verbose_name_plural = _("DeliveryTasks")
        unique_together = (("title", "created_by"))

    def __str__(self):
        return self.title


class DeliveryStateTransitionManager(models.Manager):
    def get_states_in_json(self, task_id):
        data = {
            "state": []
        }
        for transition in self.filter(task_id=task_id).order_by("at"):
            data["title"] = transition.task.title
            data["state"].append(json.loads(json.dumps({
                "at": transition.at,
                "state": transition.state.state,
                "by": transition.by.username if transition.by else None,
            }, cls=DjangoJSONEncoder)))

        return data


class DeliveryStateTransition(models.Model):
    at = models.DateTimeField(auto_now_add=True, db_index=True)
    task = models.ForeignKey(DeliveryTask, on_delete=models.CASCADE)
    state = models.ForeignKey(DeliveryTaskState, on_delete=models.CASCADE)
    by = models.ForeignKey(User,
                           on_delete=models.CASCADE,
                           null=True, blank=True,
                           db_index=True
                           )

    def __str__(self):
        return "%s_%s" % (self.task, self.state)

    class Meta:
        verbose_name = _("DeliveryStateTransition")
        verbose_name_plural = _("DeliveryStateTransitions")
        unique_together = (("task", "state", "by", "at"),)

    objects = DeliveryStateTransitionManager()

urban_piper/core/forms.py
from django.forms import ModelForm
from urban_piper.core.models import DeliveryTask


class DeliveryTaskForm(ModelForm):
    class Meta:
        model = DeliveryTask
        exclude = ("created_by", "creation_at", "assigned_to", "states")

urban_piper/core/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.safestring import mark_safe
from django.http import JsonResponse, Http404
from django.contrib import messages
from django.views import View
from urban_piper.core.forms import DeliveryTaskForm
from urban_piper.core.models import (
    DeliveryTask,
    DeliveryTaskState,
    DeliveryStateTransition
)


def index(request):
    return render(request, 'index.html', {})


class StorageManagerView(LoginRequiredMixin, View):
    template_name = "storage_manager.html"
    form_class = DeliveryTaskForm
    login_url = '/accounts/login/'
    redirect_field_name = 'sm/'

    # @storage_manager_req
    def get_context_data(self, **kwargs):
        context = {}
        context["delivery_task_form"] = self.form_class()
        """
            Get all the task created by Storage manager, along with the 
            last  known state
        """
        tasks = DeliveryTask.objects.filter(
            created_by=self.request.user).order_by("-creation_at")
        context["tasks"] = []
        for task in tasks:
            context["tasks"].append({
                "current_state": DeliveryStateTransition.objects.filter(
                                    task=task
                                    ).order_by("-at").first(),
                "task": task
            })

        return context

    def get(self, *args, **kwargs):
        if not self.request.user.is_storage_manager:
            raise Http404

        return render(self.request, self.template_name, self.get_context_data())

    def post(self, *args, **kwargs):
        """
        Save the task by ajax post request
        """
        if self.request.method == "POST" and self.request.is_ajax():
            form = self.form_class(self.request.POST)
            if form.is_valid():

                title = form.cleaned_data['title']
                created_by = self.request.user
                if DeliveryTask.objects.filter(title=title, created_by=created_by).exists():
                    return JsonResponse({
                        "success": False,
                        "errors": "Title can't be duplicated"
                    }, status=400)

                task_instance = form.save(commit=False)
                task_instance.created_by = created_by
                task_instance.save()
            else:
                return JsonResponse({
                    "success": False,
                    "errors": [(k, v[0]) for k, v in form.errors.items()]
                }, status=400)

            return JsonResponse({
                "success": True,
                "task": {
                    "id": task_instance.id,
                    "title": task_instance.title,
                    "priority": task_instance.priority,
                    "creation_at": task_instance.creation_at,
                    "created_by": task_instance.created_by.username,
                }
            }, status=200
            )
        return JsonResponse({"success": False}, status=400)


class DeliveryPersonView(LoginRequiredMixin, View):
    template_name = "delivery_person.html"
    login_url = '/accounts/login/'
    redirect_field_name = 'dp/'

    def get_context_data(self, **kwargs):
        context = {}
        """
        Pending tasks for a delivery person =
            If the user's last transitition state is accepted then,
            it is called as Pending task for the user
        """
        user_tasks = DeliveryTask.objects.filter(
            states__deliverystatetransition__by=self.request.user).distinct()
        context["pending_tasks"] = []
        for task in user_tasks:
            if task.states.all().order_by(
                "-deliverystatetransition__at"
            ).first().state == "accepted":
                context["pending_tasks"].append(task)

        return context

    def get(self, *args, **kwargs):
        if not self.request.user.is_delivery_person:
            raise Http404
        return render(self.request, self.template_name, self.get_context_data())

urban_piper/core/templates/create_task_modal.html
{% load crispy_forms_tags %}
<div class="modal fade" id="task_modal" tabindex="-1" role="dialog" aria-labelledby="task_modalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="task_modalLabel">Create Delivery Task</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" id="task_form" post_url="{% url 'core:storage_manager' %}">
                <div class="modal-body">
                    {% csrf_token %}
                    {{delivery_task_form|crispy}}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" value="Create Task">
                </div>
            </form>
        </div>
    </div>
</div>

urban_piper/core/templates/delivery_person.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container h-60">
    <div class="col-12 dp_task_pos">
        <div class="card">
            <div class="card-header">
                <p class="text-muted">You will get task here.</p>
            </div>
            <div id="new_task_card">
                <div class='card'>
                    <div class="card-body">
                        <h6 class="text-danger">No new Task available for you right now</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-12 dp_acceptedtask_pos">
        <div class="card">
            <div class="card-header">
                <p class="text-muted">Your accepted tasks will be shown below.</p>
            </div>
            <div id="accepted_task_card">
                <div class='card w-100'>
                    <div class="card-body" id="task_accepted_body">
                        {% if pending_tasks %}
                        {% for task in pending_tasks %}
                        <div class='card' data-id="{{task.id}}">
                            <div class="card-body">
                                <h5 class="card-title">{{task.title}}</h5>
                                <p>Created at: {{task.creation_at| date:"d/m/Y g:i:s A"|lower}}</p>
                            </div>
                            <div class="card-footer">
                                <button class="btn btn-primary dp_btn float-right task_completed">
                                    Complete
                                </button>
                                <button class="btn btn-danger dp_btn float-right task_declined">
                                    Decline
                                </button>
                            </div>
                        </div>
                        {% endfor %}

                        {% else %}
                        <h6 class="text-danger" id="no_accepted_task">
                            No pending tasks currently available for you.
                        </h6>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/dp.js' %}"></script>
{% endblock %}

urban_piper/core/templates/list_states_modal.html
<div class="modal  fade" id="list_state_modal" tabindex="-1" role="dialog" aria-labelledby="list_stateLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="list_state_modal">List of all states for
                    <span id="list_task_title" class="text-primary"></span>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container" id="list_state_body">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

urban_piper/core/templates/storage_manager.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% include "create_task_modal.html" %}
{% include "list_states_modal.html" %}
<div class="container sm_dashboard">
    <div class="row justify-content-end">
        <button type="button" class="btn btn-primary text-right" data-toggle="modal" data-target="#task_modal">
            Create Delivery Task</button>
    </div>
    <br>
    <div class="row">
        <div class='col-md-12 col-sm-12 col-lg-12'>
            <table class="table table-bordered" id="sm-tasktable">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Priority</th>
                        <th>Created at</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in tasks %}
                    <tr data-id="{{task.task.id}}">
                        <td class="title">{{task.task.title}}
                            <span class="badge badge-primary badge-pill current_state">
                                {{task.current_state.state | title}}
                            </span>
                        </td>
                        <td>{{task.task.priority}}</td>
                        <td>{{task.task.creation_at | date:"d/m/Y g:i:s A" | lower}}</td>
                        <td><button class="btn btn-secondary btn-sm list_state">List States</button><br>
                            {% ifequal task.current_state.state|stringformat:"s" "new" %}
                            <button class="btn btn-danger btn-sm cancel_task">Cancel Task</button>
                            {% endifequal %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/sm.js' %}"></script>
{% endblock %}